# Generated by Django 4.1.7 on 2023-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App5', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesores',
            old_name='apodo',
            new_name='especialidad',
        ),
        migrations.RenameField(
            model_name='profesores',
            old_name='ciudad',
            new_name='sede',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='telefono1',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='telefono2',
        ),
        migrations.AddField(
            model_name='profesores',
            name='cursos',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesores',
            name='edad',
            field=models.DecimalField(decimal_places=1, default=18, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesores',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
            preserve_default=False,
        ),
    ]
