# Generated by Django 4.1.7 on 2023-04-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=10)),
                ('nombre', models.TextField(max_length=20)),
                ('categoria', models.TextField(max_length=20)),
                ('color', models.TextField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.TextField(max_length=20)),
                ('telefono_prov', models.TextField(max_length=20)),
                ('fecha_llegada', models.DateField()),
                ('fecha_salida', models.DateField()),
            ],
        ),
    ]
