# Generated by Django 4.1.7 on 2023-04-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='fecha_salida',
            new_name='fecha_vencimiento',
        ),
    ]
