# Generated by Django 4.1.7 on 2023-05-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=5)),
                ('nombre', models.TextField(max_length=20)),
                ('animal', models.TextField(max_length=20)),
                ('raza', models.TextField(max_length=20)),
                ('genero', models.TextField(max_length=20)),
                ('color', models.TextField(max_length=20)),
                ('edad', models.DecimalField(decimal_places=1, max_digits=2)),
                ('nombre_dueno', models.TextField(max_length=20)),
                ('telefono', models.TextField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
