# Generated by Django 4.1.7 on 2023-05-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.TextField(max_length=10)),
                ('nombre_usu', models.TextField(max_length=50)),
                ('clave', models.TextField(max_length=20)),
            ],
        ),
    ]
