# Generated by Django 4.1.7 on 2023-05-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Punto2App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.TextField(max_length=10)),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.TextField(max_length=20)),
                ('direccion', models.TextField(max_length=20)),
                ('genero', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_cliente', models.TextField(max_length=10)),
                ('cod_lineacredito', models.TextField(max_length=10)),
                ('monto_prestado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.DateField()),
                ('fecha_desembolso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lineas_de_credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=10)),
                ('nombre_credito', models.TextField(max_length=20)),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo_maximo', models.DateField()),
            ],
        ),
    ]
