# Generated by Django 4.1.7 on 2023-05-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.TextField(max_length=10)),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=3)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.TextField(max_length=20)),
                ('sede', models.TextField(max_length=20)),
                ('carrera', models.TextField(max_length=20)),
                ('materias', models.DecimalField(decimal_places=0, max_digits=2)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
